services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        ADMIN_USERNAME: ${ADMIN_USERNAME:-twiga_admin}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD:-twiga2024!}
    container_name: twiga-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-twiga_admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-twiga2024!}
    networks:
      - twiga-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # Development service (alternative to app for development)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DATABASE_URL: ${DATABASE_URL}
        ADMIN_USERNAME: ${ADMIN_USERNAME:-twiga_admin}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD:-twiga2024!}
    container_name: twiga-dev
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-twiga_admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-twiga2024!}
    networks:
      - twiga-network
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

networks:
  twiga-network:
    driver: bridge
